server:
  port: 8082
  servlet:
    context-path: /api/v1/notification

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service?authSource=admin