server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookteria_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"


app:
  service:
    profile: http://localhost:8081/api/v1/profiles
    internal_profile: http://localhost:8081/api/v1/internal/profiles