server:
  port: 8888

app:
  api-prefix: api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
#            - Path=${app.api-prefix}/**
            - Path=/${app.api-prefix}/users/**, /${app.api-prefix}/auth/**
          filters:
            - StripPrefix=0
        - id: profile_service
          uri: http://localhost:8081
          predicates:
#            - Path=${app.api-prefix}/profiles/**
            - Path=/${app.api-prefix}/profiles/**
          filters:
            - StripPrefix=0